FROM alpine

RUN \
    echo "@edgetesting http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
    apk update && \
    apk add --no-cache \
        boost-dev \
        build-base \
        cmake \
        curl \
        git \
        libtbb@edgetesting \
        libtbb-dev@edgetesting \
        libpng-dev \
        jpeg-dev \
        tiff-dev \
        linux-headers

RUN cd /tmp && \
    git clone --branch 'master' --single-branch https://github.com/SolSpecSolutions/mvs-texturing && \
    cd /tmp/mvs-texturing && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release .. && \
    make -j $(nproc) install && \
    rm -rf /tmp/mvs-texturing
